// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVFX1pLnOFJK11i3ZM6-DNY5zlY92OYA',
    appId: '1:47472626719:web:ccbd1a69e5d3b95957192a',
    messagingSenderId: '47472626719',
    projectId: 'shopping-cart-ebaea',
    authDomain: 'shopping-cart-ebaea.firebaseapp.com',
    storageBucket: 'shopping-cart-ebaea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3vTjJhPgsd5ENA415aDe--kb_V1UAo8',
    appId: '1:47472626719:android:0eb06aa1aac8c29357192a',
    messagingSenderId: '47472626719',
    projectId: 'shopping-cart-ebaea',
    storageBucket: 'shopping-cart-ebaea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVKO5BuflCg2GRN_Gi4YBsU0mKAszQ2M',
    appId: '1:47472626719:ios:930fc6f001866ae157192a',
    messagingSenderId: '47472626719',
    projectId: 'shopping-cart-ebaea',
    storageBucket: 'shopping-cart-ebaea.firebasestorage.app',
    iosBundleId: 'rebelvi.application.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVKO5BuflCg2GRN_Gi4YBsU0mKAszQ2M',
    appId: '1:47472626719:ios:930fc6f001866ae157192a',
    messagingSenderId: '47472626719',
    projectId: 'shopping-cart-ebaea',
    storageBucket: 'shopping-cart-ebaea.firebasestorage.app',
    iosBundleId: 'rebelvi.application.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVFX1pLnOFJK11i3ZM6-DNY5zlY92OYA',
    appId: '1:47472626719:web:18cb95509ff7c08757192a',
    messagingSenderId: '47472626719',
    projectId: 'shopping-cart-ebaea',
    authDomain: 'shopping-cart-ebaea.firebaseapp.com',
    storageBucket: 'shopping-cart-ebaea.firebasestorage.app',
  );

}